insert into account_registry values('A108','Bhirud','Girish','T108');
insert into account_checking(AccountNumber,CheckingBalance) values('A108',2000.0);
insert into account_savings(AccountNumber,SavingsBalance,SavingsInterestRate) values('A108',3000.0,4.0);
insert into account_registry values('A107','Bhirud','Girish','T107');
insert into account_checking(AccountNumber,CheckingBalance) values('A107',2000.0);
insert into account_savings(AccountNumber,SavingsBalance,SavingsInterestRate) values('A107',3000.0,4.0);
insert into account_registry values('A101','Locklear','Gene','T101');
insert into account_checking(AccountNumber,CheckingBalance) values('A101',2000.0);
insert into account_savings(AccountNumber,SavingsBalance,SavingsInterestRate) values('A101',3000.0,2.0);
